name: Notice about review approved via Telegram

on:
  pull_request_review:
    types: [ submitted ]

jobs:

  build:
    if: github.event.review.state == 'commented'
    runs-on: ubuntu-latest
    steps:
      - name: Convert date format
        id: date
        run: echo "${{toJSON(github.event.pull_request.requested_reviewers) }}"