name: Notice about review approved via Telegram

on:
  pull_request_review:
    types: [ submitted ]

jobs:

  build:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2